# Generated by Django 4.0 on 2022-03-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_usergifs_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergifs',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usergifs',
            name='search_text',
            field=models.TextField(),
        ),
    ]
