# Generated by Django 4.0 on 2022-03-06 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewer', '0004_alter_usergifs_date_time_alter_usergifs_search_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergifs',
            name='user_id',
        ),
        migrations.AddField(
            model_name='usergifs',
            name='user_id',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
