# Generated by Django 4.0 on 2022-03-06 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_remove_usergifs_user_id_usergifs_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGifs',
        ),
    ]
